In [1]:
print("hello world")

hello world

# One Hot Encoding

In [4]:
import numpy as np 
import pandas as pd

In [5]:
df= pd.read_csv("cars.csv")
df.sample(10)

           brand  km_driven    fuel         owner  selling_price
1172     Hyundai      65000  Petrol   First Owner         300000
7785      Maruti     120000  Diesel   First Owner         242000
7280     Hyundai      72000  Diesel   First Owner         585000
2671       Honda      56494  Petrol   First Owner         550000
7902      Toyota     120000  Diesel   First Owner        1100000
1753  Mitsubishi     120000  Diesel  Second Owner         625000
6509      Maruti      25000  Petrol  Second Owner         180000
1746    Mahindra      80000  Diesel   First Owner         375000
3966      Datsun       5000  Petrol  Second Owner         430000
1161      Maruti      40000  Petrol  Second Owner          90000

In [16]:
df["brand"].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

## one hot encoding using pandas

In [24]:
pd.get_dummies(df,columns=["owner","fuel"],dtype=int)

,brand,km_driven,selling_price,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,Maruti,145500,450000,1,0,0,0,0,0,1,0,0
1,Skoda,120000,370000,0,0,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,1,0,0
4,Maruti,120000,130000,1,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,1,0,0,0,0,0,0,0,1
8124,Hyundai,119000,135000,0,1,0,0,0,0,1,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,1,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,1,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,1,0,0

## k-1 encoding

In [25]:
pd.get_dummies(df,columns=["owner","fuel"],dtype=int,drop_first=True)

,brand,km_driven,selling_price,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_Diesel,fuel_LPG,fuel_Petrol
0,Maruti,145500,450000,0,0,0,0,1,0,0
1,Skoda,120000,370000,0,1,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,1
3,Hyundai,127000,225000,0,0,0,0,1,0,0
4,Maruti,120000,130000,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,0,0,0,1
8124,Hyundai,119000,135000,1,0,0,0,1,0,0
8125,Maruti,120000,382000,0,0,0,0,1,0,0
8126,Tata,25000,290000,0,0,0,0,1,0,0
8127,Tata,25000,290000,0,0,0,0,1,0,0

# using sklean

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [7]:
x_train, x_test, y_train,y_test = train_test_split(df.iloc[:,:4],df.iloc[:,-1],test_size=0.2,random_state=0)

In [8]:
x_train

           brand  km_driven    fuel         owner
3042     Hyundai      60000     LPG   First Owner
1520        Tata     150000  Diesel   Third Owner
2611     Hyundai     110000  Diesel  Second Owner
3544    Mahindra      28000  Diesel  Second Owner
4138      Maruti      15000  Petrol   First Owner
...          ...        ...     ...           ...
4931        Tata      70000  Diesel   Third Owner
3264        Ford     100000  Diesel  Second Owner
1653     Hyundai      90000  Petrol  Second Owner
2607  Volkswagen      90000  Diesel   First Owner
2732     Hyundai     110000  Petrol   First Owner

[6502 rows x 4 columns]

In [22]:
ohe=OneHotEncoder(drop="first",sparse_output=False)

In [23]:
ohe.fit(x_train[["fuel","owner"]])

OneHotEncoder(drop='first', sparse_output=False)

In [24]:
x_train_encoded= ohe.transform(x_train[["fuel","owner"]])
x_test_encoded= ohe.transform(x_test[["fuel","owner"]])

x_train_encoded

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], shape=(6502, 7))

In [25]:
np.hstack((x_train[["brand","km_driven"]].values,x_train_encoded))

array([['Hyundai', 60000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Tata', 150000, 1.0, ..., 0.0, 0.0, 1.0],
       ['Hyundai', 110000, 1.0, ..., 1.0, 0.0, 0.0],
       ...,
       ['Hyundai', 90000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Volkswagen', 90000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 110000, 0.0, ..., 0.0, 0.0, 0.0]],
      shape=(6502, 9), dtype=object)

In [26]:
counts = df["brand"].value_counts()

In [29]:
counts.nunique()
threshold=50

In [38]:
rels=counts[counts<=threshold].index

In [39]:
pd.get_dummies(df["brand"].replace(rels,"uncommon"),dtype=int).sample(10)

      BMW  Chevrolet  Datsun  Ford  ...  Toyota  Volkswagen  Volvo  uncommon
5072    0          0       0     0  ...       0           0      0         0
4374    0          0       0     0  ...       0           0      0         0
3520    0          0       0     0  ...       0           0      1         0
3990    0          0       0     0  ...       0           0      0         0
2014    0          0       0     1  ...       0           0      0         0
4180    0          0       0     0  ...       0           0      0         0
4958    0          0       0     0  ...       0           0      0         0
5621    0          0       0     0  ...       0           0      0         0
3222    0          0       0     0  ...       0           0      0         0
150     0          0       0     0  ...       0           0      0         0

[10 rows x 18 columns]